---
title: "Audit Analytics"
format: gfm
---

Data found in `audit` schema of the WRDS PostgreSQL database.

## Introduction
[Audit Analytics](https://www.auditanalytics.com/) "is an independent research provider of audit, regulatory and disclosure intelligence. Audit Analytics provides detailed data on over 150,000 active audits and more than 10,000 accounting firms." Please refer to the [Manuals and Overviews](https://wrds-www.wharton.upenn.edu/pages/support/manuals-and-overviews/audit-analytics/) or download a [zip file](https://github.com/mccgr/wrds_pg/blob/master/audit/AuditAnalyticsManuals.zip?raw=true) to view the data structures and variable definitions of Audit Analytics via WRDS.

## List of datasets imported

Audit Analytics comprises five sets of data:

 1. Audit and Compliance
 2. Corporate and Legal
 3. Accounting and Oversight
 4. Other Independent Audit
 5. Canada (SEDAR)

The University of Melbourne currently has subscriptions to the first three sets of data.

### Audit and Compliance

This comprises 14 tables (table names listed in parentheses):

- Auditors (`feed01_auditors`)
- Auditor Changes (`feed02_auditor_changes`)
- Audit Fees (`feed03_audit_fees`)
- Audit Fees with Restatements (`feed04_audit_fees_restated`)
- Benefit Plan Opinions (`feed06_benefit_plan_opinions`)
- Current Auditors (`feed07_current_auditor`)
- Auditor During (`feed08_auditor_during`)
- SOX 302 Disclosure Controls (`feed10_sox_302_disclosure_contro`)
- SOX 404 Internal Controls (`feed11_sox_404_internal_controls`)
- Accelerated Filer (`feed16_accelerated_filer`)
- Director and Officer Changes (`feed17_director_and_officer_chan`)
- Non-timely Filer Information And Analysis (`feed20_nt`)
- Revised Audit Opinions (`feed34_revised_audit_opinions`)
- Financial Restatements (`feed39_financial_restatements`)

### Corporate and Legal

This comprises 12 tables (table names listed in parentheses):

 - Legal Case (`feed13_legal_case_feed`)
 - Legal Parties (`feed14_company_legal_party_feed`)
 - Mergers and Acquisitions (`feed18_merger_acquisition`)
 - IPO (`feed19_ipo`)
 - Bankruptcy Notification (`feed21_bankruptcy_notification`)
 - Comment Letter (`feed25_comment_letters`)
 - Comment Letter Conversations (`feed26_comment_letter_conversati`) 
 - Shareholder Activism (`feed31_shareholder_activism`)
 - Form D (`feed37_form_d`)
 - Form D Most Recent Report (`feed38_form_d_most_recent_offeri`)
 - Comment Threading (`feed40_comment_letter_threads`)
 - Transfer Agents (`feed41_transfer_agents`)
 
### Accounting and Oversight

This comprises 9 tables (table names listed in parentheses):

 - Auditor Ratification (`feed55_auditor_ratification`
 - Accounting Estimates Change (`feed56_accounting_estimates_chan`)	
 - Impairments (`feed65_impairments`)
 - Accounting Quality Risk Matrix (AQRM) (`feed74_aqrm`)	
 - Critical Audit Matters (`feed78_critical_audit_matters`)
 - Cybersecurity (`feed85_cybersecurity`)	
 - Audit Firm Events (`feed86_audit_firm_events`)	
 - PCAOB Report (`feed89_pcaob_report`)
 - AAER (`feed91_aaer`)
 
In each case, the database includes a table with the same name, but in general, we do not include *all* variables provided in the WRDS version of the table.
A detailed discussion of the changes we make is given below.

## Issues identified

While Audit Analytics provides comprehensive data, the tables provided by WRDS, unfortunately, are a complete mess and the data are often not well-formatted.
One particular issue is that the tables are very much *not* normalized.
So there is a lot of duplicated data and tables are loaded with extraneous information.
Also, some textual variables create problems.
We identified the following two issues.

### Omission of financial variables

Specifically, the WRDS tables often include variables from the "company financial block", which are financial statement variables such as net income or total assets for the "`closest`", "`match`", "`hiwater`", or "`prior`" periods (either quarters [`qu`] or years [`yr`]).
These variables expand the size of the tables dramatically, and their provenance is unclear (likely scraped from SEC filings, which are the primary source for Audit Analytics data).
Also, the meaning of the terms "`closest`", "`match`", "`hiwater`", and "`prior`" is unclear and the data are very poorly documented on WRDS.
So, we simply omit these variables when importing the data.

### Omission of textual variables

One or two fields from each of two tables are omitted because they are two big to be processed by `db2pq` (due to limitaions in PyArrow or DuckDB):

 - `feed17_director_and_officer_chan`: `do_change_text`
 - `feed25_comment_letters`: `cl_text`, `cl_frmt_text_html`
