#!/usr/bin/env python3
from db2pq import wrds_update_pq

# Legal Case And Legal Parties
wrds_update_pq("feed13_legal_case_feed", "audit",
                      col_types={'legal_case_key': 'int32',
                                 'der_legal_case_fkey': 'int32',
                                 'cross_claim': 'boolean',
                                 'counter_claim': 'boolean',
                                 'lit_legal_case_outcome_fkey': 'int32',
                                 'is_category_type_1': 'boolean',
                                 'is_category_type_2': 'boolean',
                                 'is_category_type_3': 'boolean',
                                 'is_category_type_4': 'boolean',
                                 'is_category_type_5': 'boolean',
                                 'is_category_type_6': 'boolean',
                                 'is_category_type_7': 'boolean',
                                 'is_category_type_8': 'boolean',
                                 'is_category_type_9': 'boolean',
                                 'is_category_type_10': 'boolean',
                                 'is_category_type_11': 'boolean',
                                 'is_category_type_12': 'boolean',
                                 'is_category_type_13': 'boolean',
                                 'is_category_type_14': 'boolean',
                                 'is_category_type_15': 'boolean',
                                 'is_category_type_16': 'boolean',
                                 'is_category_type_17': 'boolean',
                                 'is_category_type_18': 'boolean',
                                 'is_category_type_19': 'boolean',
                                 'is_category_type_20': 'boolean',
                                 'is_category_type_21': 'boolean',
                                 'is_category_type_22': 'boolean',
                                 'is_category_type_23': 'boolean',
                                 'is_category_type_24': 'boolean',
                                 'is_category_type_25': 'boolean',
                                 'is_category_type_26': 'boolean',
                                 'is_category_type_28': 'boolean',
                                 'is_category_type_29': 'boolean',
                                 'is_category_type_30': 'boolean',
                                 'is_category_type_31': 'boolean',
                                 'is_category_type_32': 'boolean',
                                 'is_category_type_33': 'boolean',
                                 'is_category_type_34': 'boolean',
                                 'is_category_type_35': 'boolean',
                                 'is_category_type_36': 'boolean',
                                 'is_category_type_37': 'boolean',
                                 'is_category_type_38': 'boolean',
                                 'is_category_type_39': 'boolean',
                                 'is_category_type_40': 'boolean',
                                 'is_category_type_41': 'boolean',
                                 'is_category_type_42': 'boolean',
                                 'is_category_type_43': 'boolean',
                                 'is_category_type_44': 'boolean',
                                 'is_category_type_48': 'boolean',
                                 'is_category_type_49': 'boolean',
                                 'is_category_type_50': 'boolean',
                                 'is_category_type_51': 'boolean',
                                 'is_category_type_52': 'boolean',
                                 'is_category_type_53': 'boolean',
                                 'is_category_type_54': 'boolean',
                                 'is_category_type_55': 'boolean',
                                 'is_category_type_56': 'boolean',
                                 'is_category_type_57': 'boolean',
                                 'is_category_type_58': 'boolean',
                                 'is_category_type_59': 'boolean',
                                 'is_category_type_60': 'boolean',
                                 'is_category_type_61': 'boolean',
                                 'is_category_type_62': 'boolean',
                                 'is_category_type_63': 'boolean',
                                 'is_category_type_64': 'boolean',
                                 'is_category_type_66': 'boolean',
                                 'is_category_type_67': 'boolean',
                                 'is_category_type_68': 'boolean',
                                 'is_category_type_69': 'boolean',
                                 'is_category_type_70': 'boolean',
                                 'is_category_type_71': 'boolean',
                                 'is_category_type_72': 'boolean',
                                 'is_category_type_73': 'boolean',
                                 'is_category_type_74': 'boolean',
                                 'is_category_type_75': 'boolean',
                                 'is_category_type_76': 'boolean',
                                 'is_category_type_77': 'boolean',
                                 'is_category_type_78': 'boolean',
                                 'is_category_type_79': 'boolean',
                                 'is_category_type_80': 'boolean',
                                 'is_category_type_81': 'boolean',
                                 'is_category_type_82': 'boolean',
                                 'is_category_type_83': 'boolean',
                                 'is_category_type_84': 'boolean',
                                 'is_category_type_85': 'boolean',
                                 'is_category_type_86': 'boolean',
                                 'is_category_type_87': 'boolean',
                                 'is_category_type_88': 'boolean',
                                 'is_category_type_89': 'boolean',
                                 'is_category_type_90': 'boolean',
                                 'is_category_type_91': 'boolean',
                                 'is_category_type_92': 'boolean',
                                 'is_category_type_93': 'boolean',
                                 'is_category_type_94': 'boolean',
                                 'is_category_type_95': 'boolean',
                                 'is_category_type_96': 'boolean',
                                 'is_category_type_97': 'boolean',
                                 'is_category_type_98': 'boolean',
                                 'is_category_type_99': 'boolean',
                                 'is_category_type_100': 'boolean',
                                 'is_category_type_101': 'boolean',
                                 'is_category_type_102': 'boolean',
                                 'is_category_type_103': 'boolean',
                                 'is_category_type_105': 'boolean',
                                 'is_category_type_106': 'boolean',
                                 'is_category_type_107': 'boolean',
                                 'is_category_type_108': 'boolean',
                                 'is_category_type_109': 'boolean',
                                 'law_court_key': 'int32',
                                 'court_type_code': 'int32',
                                 'judge_key': 'int32',
                                 'magistrate': 'boolean',
                                 'gender': 'int32'})

wrds_update_pq("feed14_company_legal_party_feed", "audit",
                       drop="^(match|prior|closest)", # web_summ
                      col_types={"legal_party_key":"int32",
                                 "auditor_key":"int32",
                                    "gov_key":"int32",
                                    "law_firm_key":"int32",
                                    "legal_case_key":"int32",
                                    "is_creditor": "boolean",
                                    "is_debtor": "boolean", 
                                    "is_non_party_par": "boolean",   
                                    "is_nom_defendant": "boolean", 
                                    "is_pcaob_reg": "boolean", 
                                    "is_active": "boolean", 
                                    "cross_claim": "boolean",
                                    "counter_claim": "boolean",
                                    "law_court_fkey": "int32",
                                    "judge_fkey": "int32",
                                    "deriv_lega_case_fkey": "int32",
                                    "eventdate_aud_fkey": "int32",
                                    "defendant":"boolean",   
                                    "plaintiff":"boolean",
                                    "is_lead":"boolean",         
                                    "been_terminated":"boolean",
                                    "consol":"boolean",
                                    "rel_non_party":"boolean",
                                    "rel_defendant":"boolean",
                                    "third_party":"boolean"})

# Mergers and Acquisitions
wrds_update_pq("feed18_merger_acquisition", "audit",
                      col_types={"ma_party_key": "int32",
                                 "party_co_fkey": "int32",
                                 "party_aud_fkey": "int32",
                                 "trans_val_est": "boolean",
                                 "is_canceled": "boolean",
                                 "deal_confirmed": "boolean",
                                 "m_a_key": "int32",
                                 "ma_transaction_type_fkey": "int32",
                                 "eventdate_aud_fkey": "int32"},
                       drop="^(match|prior|closest)")

# IPO
wrds_update_pq("feed19_ipo", "audit",
                      drop="^(match|prior|closest)",
                      col_types={"ipo_info_key": "int32",
                                   "auditor_fkey_at_ipo": "int32",
                                   "eventdate_aud_fkey": "int32"})
# Bankruptcy Notification
wrds_update_pq("feed21_bankruptcy_notification", "audit",
                      drop="^(match|prior|closest)",
                      col_types={"bank_key": "int32",
                                   "bankruptcy_type": "int32",
                                   "law_court_fkey": "int32",
                                   "file_accepted": "timestamp",
                                   "eventdate_aud_fkey": "int32"})

# Comment Letters
wrds_update_pq("feed25_comment_letters", "audit",
                      col_types={"cl_con_id": "int32"},
                      drop="^(closest|cl_text|cl_frmt_text_html)",
                      alt_table_name="feed25_comment_letters")

#wrds_update_pq("feed25_comment_letters", "audit", force=True,
#                col_types={"cl_con_id": "int32",
#                           "cl_text": "string"},
#                      keep="^(cl_letter_ftpfilekey|cl_text)",
#                    alt_table_name="feed25_text")

# Comment Letter Conversations
wrds_update_pq("feed26_comment_letter_conversati", "audit",
                      drop = "^closest",
                      col_types={'cl_con_id': 'int32', 
                                   'con_time_span': 'int32'})

# Comment Threading
wrds_update_pq("feed40_comment_letter_threads", "audit",
                       drop="^(match|prior|closest)",
                      col_types={'comment_response_key': 'int32', 
                                 'ques_cl_comment_fkey': 'int32', 
                                 'eventdate_aud_fkey': 'int32'})

# Transfer Agents
wrds_update_pq("feed41_transfer_agents", "audit",
                       drop="^(match|prior|closest)",
                      col_types={"transfer_agent_company_fkey": "int32",
                                 "company_to_transfer_agent_key":"int32",
                                 "filed_for_company_fkey": "int32",
                                 "mr_transfer_agent_file_date":"date",
                                 "mr_transfer_age_reg_fil_dat": "date",
                                 "shareholder_company_fkey": "int32",
                                 "shareholder_info_key": "int32",
                                 "mr_transfer_age_der_fil_dat": "date",
                                 "shareholder_class_fkey": "int32",
                                 "transfer_agent_ult_par_com_fke": "int32",
                                 "shareholder_market_fkey": "int32",
                                 "eventdate_aud_fkey": "int32"})

# Tax Footnotes
wrds_update_pq("feed32_tax_footnotes", "audit", 
                        col_types={"tax_footnote_key": "int32",
                                   "times_restated": "int32",
                                   "res_notif_fkey": "int32",
                                   "eventdate_aud_fkey": "int32",
                                   "file_date": "date"},
                         drop="^(match|prior|closest)")

# Shareholder Activism
wrds_update_pq("feed31_shareholder_activism", "audit",
                       drop="^(match|prior|closest)",
                      col_types={'active_share_key':'int32',
                                   'active_share_rep_fkey': 'int32',
                                   'iss_file_accepted': 'timestamp',
                                   'rep_file_acc': 'timestamp',
                                   'dispute_management': 'boolean',
                                   'eventdate_aud_fkey': 'int32'})

# Form D
wrds_update_pq("feed37_form_d", "audit",
                      col_types={"form_d_key": "int32",
                                   "authorized_representative": "boolean",
                                   "is_business_com_tra": "boolean",
                                   "file_accepted":"timestamp",
                                   "is_primary": "boolean"})

# Form D Most Recent Report
wrds_update_pq("feed38_form_d_most_recent_offeri", "audit",
                      col_types={"form_d_key": "int32", 
                                   "file_accepted": "timestamp",
                                   "primary_issuer_company_fkey": "int32",
                                   "has_non_accredited_investors": "boolean",
                                   "authorized_representative": "boolean",
                                   "gross_proceeds_use_est": "boolean",
                                   "is_business_com_tra": "boolean",
                                   "total_offering_is_indefinite": "boolean",
                                   "is_primary": "boolean"})
