#!/usr/bin/env python3
from db2pq import wrds_update_pq

wrds_update_pq("aco_pnfnda", "comp")
wrds_update_pq("adsprate", "comp")
wrds_update_pq("anncomp", "comp_execucomp", sas_schema="comp")
wrds_update_pq("co_adesind", "comp")
wrds_update_pq("co_afnd2", "comp")
wrds_update_pq("co_filedate", "comp")
wrds_update_pq("co_hgic", "comp")
wrds_update_pq("co_ifndq", "comp")
wrds_update_pq("company", "comp")
wrds_update_pq("funda", "comp")
wrds_update_pq("funda_fncd", "comp")
wrds_update_pq("fundq", "comp")
wrds_update_pq("fundq_fncd", "comp")
wrds_update_pq("g_chars", "comp")
wrds_update_pq("g_company", "comp")
wrds_update_pq("g_exrt_dly", "comp")
wrds_update_pq("g_funda", "comp")
wrds_update_pq("g_idx_index", "comp")
wrds_update_pq("g_idx_mth", "comp")
wrds_update_pq("g_idxcst_his", "comp")
wrds_update_pq("g_names", "comp")
wrds_update_pq("g_names_ix", "comp")
wrds_update_pq("g_names_ix_cst", "comp")
wrds_update_pq("g_namesq", "comp")
wrds_update_pq("g_sec_divid", "comp")
wrds_update_pq("g_secd", "comp")
wrds_update_pq("g_secm", "comp")
wrds_update_pq("g_secnamesd", "comp")
wrds_update_pq("g_security", "comp")
wrds_update_pq("idx_ann", "comp")
wrds_update_pq("idx_index", "comp")
wrds_update_pq("idxcst_his", "comp")
wrds_update_pq("io_qbuysell", "comp")
wrds_update_pq("names", "comp")
wrds_update_pq("names_ix", "comp")
wrds_update_pq("r_auditors", "comp")
wrds_update_pq("r_datacode", "comp")
wrds_update_pq("r_fndfntcd", "comp")
wrds_update_pq("r_giccd", "comp")
wrds_update_pq("sec_divid", "comp")
wrds_update_pq("sec_history", "comp")
wrds_update_pq("secd", "comp")
wrds_update_pq("secm", "comp", col_types = {'cshom' : 'float64'})
wrds_update_pq("seg_annfund", "comp")
wrds_update_pq("seg_customer", "comp")
wrds_update_pq("spind_mth", "comp")
wrds_update_pq("wrds_seg_customer", "comp")
wrds_update_pq("wrds_segmerged", "comp")
wrds_update_pq("wrds_ciqsymbol", "ciq",
               col_types = {'companyid':'int32',
                            'symbolid':'int32',
                            'objectid':'int32'})
